# Use the official Flutter lint rules as a base
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"        # json_serializable, freezed generated files
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - ".dart_tool/**"
    - "build/**"
    - ".github/**"
    - "coverage/**"
    - "ios/**"
    - "android/**"
    - "web/**"
    - "test/**"
    - "generated/**"

linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - annotate_overrides
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_redundant_argument_values
    - avoid_positional_boolean_parameters
    - avoid_single_cascade_in_expression_statements
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_spread_collections
    - prefer_if_null_operators
    - prefer_collection_literals
    - prefer_typing_uninitialized_variables
    - require_trailing_commas
    - use_key_in_widget_constructors
    - prefer_const_constructors_in_immutables
    - sort_constructors_first
    - unnecessary_null_in_if_null_operators
    - use_late_for_private_fields
    - avoid_unused_constructor_parameters
