import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:rolla_demo_app/core/presentation/bloc/locale_cubit.dart';
import 'package:rolla_demo_app/core/presentation/bloc/theme_cubit.dart';

import 'core/di/scores_injection.dart' as di;
import 'core/localization/localization_service.dart';
import 'core/theme/app_theme.dart';
import 'features/scores/presentation/pages/home_page.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await di.init(); // register dependencies

  // decide initial locale; load it before runApp so `tr` is available immediately
  final initialLocale = const Locale(
    'en',
  ); // or load from persisted user settings
  await LocalizationService.instance.load(initialLocale);

  runApp(
    MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => LocaleCubit(initialLocale)),
        BlocProvider(create: (_) => ThemeCubit(ThemeMode.system)),
      ],
      child: const RollaApp(),
    ),
  );
}

class RollaApp extends StatefulWidget {
  const RollaApp({Key? key}) : super(key: key);

  @override
  State<RollaApp> createState() => _RollaAppState();
}

class _RollaAppState extends State<RollaApp> {
  @override
  Widget build(BuildContext context) {
    return Builder(
      builder: (context) {
        final locale = context.watch<LocaleCubit>().state;
        final themeMode = context.watch<ThemeCubit>().state;

        return MaterialApp(
          title: 'Rolla Demo',
          theme: AppTheme.light,
          darkTheme: AppTheme.dark,
          themeMode: themeMode,
          locale: locale,
          supportedLocales: LocalizationService.supportedLocales,
          localizationsDelegates: const [
            // AppLocalizations delegate generated by intl_utils
            LocalizationService.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          home: HomePage(),
        );
      },
    );
  }
}
