import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'core/di/scores_injection.dart' as di;
import 'core/localization/locale_setup.dart';
import 'core/theme/app_theme.dart';
import 'features/scores/presentation/pages/home_page.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await di.init(); // register dependencies
  await LocaleSetup.init(); // pre-load localization (intl utils generated)
  runApp(const RollaApp());
}

class RollaApp extends StatefulWidget {
  const RollaApp({Key? key}) : super(key: key);

  @override
  State<RollaApp> createState() => _RollaAppState();
}

class _RollaAppState extends State<RollaApp> {
  ThemeMode _themeMode = ThemeMode.system;
  Locale? _locale;

  void _setTheme(ThemeMode mode) => setState(() => _themeMode = mode);
  void _setLocale(Locale locale) => setState(() => _locale = locale);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Rolla Demo',
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: _themeMode,
      locale: _locale,
      supportedLocales: LocaleSetup.supportedLocales,
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        // AppLocalizations delegate generated by intl_utils
        LocaleSetup.delegate,
      ],
      home: HomePage(
        onChangeTheme: _setTheme,
        onChangeLocale: _setLocale,
      ),
    );
  }
}
