import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

// NOTE: AppLocalizations is generated by intl_utils from lib/l10n/*.arb
import '../../generated/l10n.dart'; // if intl_utils was configured -> adjust path

class LocaleSetup {
  static const AppLocalizationDelegate delegate = S.delegate;

  static const supportedLocales = [
    Locale('en'),
    Locale('hr'),
  ];

  static Future<void> init() async {
    // Nothing heavy to do here by default - intl_utils generate provides S.delegate
    // But we ensure default formatting for dates:
    Intl.defaultLocale = 'en';
  }

  static void setLocale(Locale locale) {
    Intl.defaultLocale = locale.languageCode;
  }
}
