import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

// NOTE: AppLocalizations is generated by intl_utils from lib/l10n/*.arb
import '../../generated/l10n.dart'; // if intl_utils was configured -> adjust path

class LocalizationService {
  LocalizationService._();
  static final LocalizationService instance = LocalizationService._();

  static const AppLocalizationDelegate delegate = S.delegate;
  static const supportedLocales = [Locale('en'), Locale('hr')];

  S? _strings;
  Locale? _locale;

  /// loaded strings (can be null until loaded)
  S? get strings => _strings;
  Locale? get currentLocale => _locale;

  /// Load and set locale; updates Intl.defaultLocale
  Future<void> load(Locale locale) async {
    // ensure the locale string for intl
    Intl.defaultLocale = locale.toLanguageTag();
    _strings = await S.delegate.load(locale);
    _locale = locale;
  }

  static void setLocale(Locale locale) {
    Intl.defaultLocale = locale.languageCode;
  }
}
